### ISSUE TITLE
[Setting] DB 연결, JPA 설정, 공통 Response Type 생성

### ISSUE THREAD

**Issue by HyungcheolSim** [HyungcheolSim/OwnWillU#3]
## 📝 개요
- DB 연결
- JPA 연동
- 공통 Response 생성
- 테스트 코드 작성

## ✅ TO-DO
- [x] DB 생성, 연결
- [x] JPA연동 
- [x] 간단한 User Entity, Repository 작성
- [x] User CREATE, READ 테스트 코드 작성
- [x] 일반적으로 Status, Message, (Data)를 담을 수 있는 DTO 객체 생성

## 📌 ETC
-
