### ISSUE TITLE
[Setting] log설정

### ISSUE THREAD

**Issue by HyungcheolSim** [HyungcheolSim/OwnWillU#4]
## 📝 개요
- 어떤 로그 라이브러리 사용할지 의사결정
- log 콘솔 및 파일로 관리할 목적으로 저장

## ✅ TO-DO
- [x] 로그 라이브러리 선택 (log4j2, logback....)
- [x] 로그를 남길 곳 선택
   Controller, Service 후에 Filter...Util class 등..
- [x] 로그를 남기는 방법 선택
   일단 내가 원하는 api에 관련된 로그는 각각의 파일에서 작성
++계속 생각해서 추가
- [x] 로그 관련 설정

## 📌 ETC
- 관련 문서 [[의사결정]Logging](https://sim34122.oopy.io/91d5e6c0-6cf7-41a2-b7d1-fb0716d7bfd9)
- 로그는 개발 과정에서 무수한 개선 여지가 있다!!!
