### ISSUE TITLE
[Feat] SpringSecurity 적용 & JWT 적용

### ISSUE THREAD

**Issue by HyungcheolSim** [HyungcheolSim/OwnWillU#9]
## 📝 개요
-  SpringSecurity 적용
- JWT 적용

## ✅ TO-DO
- [ ] SpringSecurity 보강 학습
- [ ] SpringSecurity 적용 방식 결정(Filter or Interceptor or else?)
- [ ] JWT 안에 들어가는 내용, Secret Key 직접 설정하기

## 📌 ETC
-

**Comment by HyungcheolSim** [comment]
후에 토큰 개선 적용할만한 링크
[JJWT](https://samtao.tistory.com/65) 
[토큰에 부가 정보 담기](https://kimjingyu.tistory.com/entry/JWTJSON-Web-Token)
